### ISSUE TITLE
Bug with Cloudflare R2

### ISSUE THREAD

**Issue by rakataprime** [rodneylab/sveltekit-s3-multipart-upload#1]
**Describe the bug**

When you try to use this with Cloudflare R2 it doesn't work giving an error:
Error in handleSubmit on / route: TypeError: Cannot read properties of undefined (reading 'forEach')

Error: Invalid response from route /api/presigned-urls.json: handler should return a Response object

**To Reproduce**
clone main branch, 
update line 29 of storage.js with 	fetch(`https://${S3_COMPATIBLE_ACCOUNT_ID}.r2.cloudflarestorage.com`,
update .env with cloudflare r2 credentials

Here is a link to the cloudflare r2 example for aws-sdk-js
https://developers.cloudflare.com/r2/examples/aws/aws-sdk-js-v3/

**Expected behaviour**
 
the api to to return a response with the error message included

**Screenshots**

**Desktop (please complete the following information):**

- OS: arch linux
- Browser thorium/ chromium  
- Version 109.0.5361.0

**Smartphone (please complete the following information):**
NA
**Additional context**
NA

**Comment by rodneylab** [comment]
Hey @rakataprime, thanks for reaching out.  I think this has been fixed now. Hopefully it is working for you.

**Comment by rodneylab** [comment]
Closing due to lack of actvity
